<?php

use Kernel\Io\Convert\Image;
use Kernel\Security\Vulnerability\Xss;
use Kernel\Security\Vulnerability\Csrf;
use Kernel\Html\Attribute;
use Kernel\Html\Builder;
use Kernel\Html\Output;
use Kernel\Url\Location;
?>



<!-- 
Vue du composant Modal.
Author: chris
Version: 1.0
Categorie: Component template
 -->
<modal>
    <div class="content">
        <span class="close">X</span>

    </div>

</modal>